{% set name = "SPARC-X-API" %}
{% set version = "1.0.6" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SPARC-X/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b730f82d29303a13b070442c56f5a278ec315beea8d6516e8e6238796a8a0120

build:
  noarch: python
  number: 0
  # Install and include the psp files
  script: "{{ PYTHON }} -m pip install . --no-deps -vv && cd .. && {{ PYTHON }} -m sparc.download_data"
  entry_points:
    - "sparc-ase = sparc.cli:main"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.22
    - numpy >=1.23
    - packaging >=20.0
    - psutil >=5.0.0

test:
  imports:
    - sparc
    - sparc.io
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - python -m sparc.quicktest
    - python -c "from sparc.quicktest import PspTest; PspTest()"

about:
  home: https://github.com/SPARC-X/SPARC-X-API
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "SPARC-X-API: A Python API for the SPARC-X DFT Code"
  description: |
    `SPARC-X-API` is an [ASE](https://wiki.fysik.dtu.dk/ase/)-compatible Python API for the density functional theory (DFT) code [SPARC](https://github.com/SPARC-X/SPARC). It offers:
    1. ASE-compatible I/O format for SPARC files
    2. A JSON API interfacing with SPARC's C-code for parameter validation and conversion
    3. A comprehensive calculator interface for SPARC.
  doc_url: https://sparc-x.github.io/SPARC-X-API/
  dev_url: https://sparc-x.github.io/SPARC-X-API/contribute.html

extra:
  recipe-maintainers:
    - alchem0x2a
